In [3]:
import numpy as np
import nibabel as nib

# Voxel sizes in each dimension (x, y, z)
voxel_sizes = (0.4143, 0.4143, 0.4000)  # Replace with your actual voxel sizes

# Dimensions of the image (number of voxels in each dimension)
image_dimensions = (512, 512, 311)  # Replace with your actual image dimensions

# Orientation information (optional)
# If your data is already in a standard orientation, you may not need to modify this part.
# orientation = np.eye(3)  # Identity matrix for standard orientation

# Origin in real-world coordinates
origin = (91.7828445435, 94.0881500244, -1115.8076171875)  # Replace with your actual origin

# IJK to RAS Direction matrix (replace with your values)
ijk_to_ras_direction_matrix = np.array([
    [-1.0, 0.0, 0.0],
    [0.0, 1.0, 0.0],
    [0.0, 0.0, 1.0]
])

# Create the affine matrix
affine_matrix = np.eye(4)

# Set the voxel sizes and dimensions in the diagonal
for i in range(3):
    affine_matrix[i, i] = voxel_sizes[i]
    affine_matrix[i, 3] = -voxel_sizes[i] * image_dimensions[i] / 2.0  # Adjust for the center of the image

# Set the orientation and origin
# Uncomment and replace with your orientation matrix if needed
affine_matrix[:3, :3] = ijk_to_ras_direction_matrix * np.diag(voxel_sizes)
affine_matrix[:3, 3] = origin

In [4]:
print(affine_matrix)

[[-4.14300000e-01  0.00000000e+00  0.00000000e+00  9.17828445e+01]
 [ 0.00000000e+00  4.14300000e-01  0.00000000e+00  9.40881500e+01]
 [ 0.00000000e+00  0.00000000e+00  4.00000000e-01 -1.11580762e+03]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
